test action for deb-s3

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,8 +1,10 @@
 name: Publish
 on:
   push:
-    tags:
-      - v*.*.*
+    branches:
+      - apt_repository
+    # tags:
+    #   - v*.*.*
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -153,96 +155,117 @@ jobs:
           asset_name: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.deb
           asset_content_type: application/octet-stream
 
+      # - name: Upload DEB to apt repository on s3
+      #   if: matrix.build != 'freebsd'
+      #   run: |
+      #     export PATH="/srv/github/defguard/.local/share/gem/ruby/3.3.0/bin:$PATH"
+      #     COMPONENT=$([[ "${{ github.ref_name }}" == *"-"* ]] && echo "pre-release" || echo "release") # if tag contain "-" assume it's pre-release.
+
+      #     deb-s3 upload -l --bucket=apt.defguard.net --access-key-id=${{ secrets.AWS_ACCESS_KEY_APT }} --secret-access-key=${{ secrets.AWS_SECRET_KEY_APT }} --s3-region=eu-north-1 --no-fail-if-exists --codename=trixie --component="$COMPONENT" defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.deb
+
+      - name: Setup deb-s3
+        if: matrix.build != 'freebsd'
+        uses: deb-s3/setup-deb-s3@v1
+
       - name: Upload DEB to apt repository on s3
         if: matrix.build != 'freebsd'
         run: |
-          export PATH="/srv/github/defguard/.local/share/gem/ruby/3.3.0/bin:$PATH"
-          COMPONENT=$([[ "${{ github.ref_name }}" == *"-"* ]] && echo "pre-release" || echo "release") # if tag contain "-" assume it's pre-release.
+          COMPONENT=$([[ "${{ github.ref_name }}" == *"-"* ]] && echo "pre-release" || echo "release")
+          
+          deb-s3 upload \
+            --bucket=apt.defguard.net \
+            --access-key-id=${{ secrets.AWS_ACCESS_KEY_APT }} \
+            --secret-access-key=${{ secrets.AWS_SECRET_KEY_APT }} \
+            --s3-region=eu-north-1 \
+            --codename=trixie \
+            --component="$COMPONENT" \
+            --no-fail-if-exists \
+            defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.deb
 
-          deb-s3 upload -l --bucket=apt.defguard.net --access-key-id=${{ secrets.AWS_ACCESS_KEY_APT }} --secret-access-key=${{ secrets.AWS_SECRET_KEY_APT }} --s3-region=eu-north-1 --no-fail-if-exists --codename=trixie --component="$COMPONENT" defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.deb
-      - name: Run `packer init`
-        if: matrix.build == 'linux' && matrix.arch == 'amd64'
-        id: init
-        run: "packer init ./images/ami/gateway.pkr.hcl"
 
-      - name: Build AMI images for multiple regions
-        if: matrix.build == 'linux' && matrix.arch == 'amd64'
-        run: |
-          regions=(us-east-1 eu-west-1 ap-northeast-1 eu-central-1)
-          for region in "${regions[@]}"; do
-            echo "Building AMI for region: $region"
-            echo "Running packer validate for $region..."
-            packer validate --var "package_version=${{ env.VERSION }}" --var "region=$region" ./images/ami/gateway.pkr.hcl
-            echo "Building AMI image for $region..."
-            packer build -color=false -on-error=abort --var "package_version=${{ env.VERSION }}" --var "region=$region" ./images/ami/gateway.pkr.hcl
-          done
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      # - name: Run `packer init`
+      #   if: matrix.build == 'linux' && matrix.arch == 'amd64'
+      #   id: init
+      #   run: "packer init ./images/ami/gateway.pkr.hcl"
 
-      - name: Build RPM package
-        if: matrix.build == 'linux'
-        uses: defGuard/fpm-action@main
-        with:
-          fpm_args: "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/sbin/defguard-gateway defguard-gateway.service=/usr/lib/systemd/system/defguard-gateway.service example-config.toml=/etc/defguard/gateway.toml.sample"
-          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type rpm --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm --after-install after-install.sh"
+      # - name: Build AMI images for multiple regions
+      #   if: matrix.build == 'linux' && matrix.arch == 'amd64'
+      #   run: |
+      #     regions=(us-east-1 eu-west-1 ap-northeast-1 eu-central-1)
+      #     for region in "${regions[@]}"; do
+      #       echo "Building AMI for region: $region"
+      #       echo "Running packer validate for $region..."
+      #       packer validate --var "package_version=${{ env.VERSION }}" --var "region=$region" ./images/ami/gateway.pkr.hcl
+      #       echo "Building AMI image for $region..."
+      #       packer build -color=false -on-error=abort --var "package_version=${{ env.VERSION }}" --var "region=$region" ./images/ami/gateway.pkr.hcl
+      #     done
+      #   env:
+      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      - name: Upload RPM
-        if: matrix.build == 'linux'
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ needs.create-release.outputs.upload_url }}
-          asset_path: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm
-          asset_name: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm
-          asset_content_type: application/octet-stream
+      # - name: Build RPM package
+      #   if: matrix.build == 'linux'
+      #   uses: defGuard/fpm-action@main
+      #   with:
+      #     fpm_args: "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/sbin/defguard-gateway defguard-gateway.service=/usr/lib/systemd/system/defguard-gateway.service example-config.toml=/etc/defguard/gateway.toml.sample"
+      #     fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type rpm --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm --after-install after-install.sh"
 
-      - name: Build FreeBSD package
-        if: matrix.build == 'freebsd'
-        uses: defGuard/fpm-action@main
-        with:
-          fpm_args:
-            "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/local/sbin/defguard-gateway
-            defguard-gateway.service.freebsd=/usr/local/etc/rc.d/defguard_gateway
-            example-config.toml=/etc/defguard/gateway.toml.sample
-            defguard-rc.conf=/etc/rc.conf.d/defguard_gateway"
-          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type freebsd --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg --freebsd-osversion '*'"
+      # - name: Upload RPM
+      #   if: matrix.build == 'linux'
+      #   uses: actions/upload-release-asset@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     upload_url: ${{ needs.create-release.outputs.upload_url }}
+      #     asset_path: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm
+      #     asset_name: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.rpm
+      #     asset_content_type: application/octet-stream
 
-      - name: Upload FreeBSD
-        if: matrix.build == 'freebsd'
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ needs.create-release.outputs.upload_url }}
-          asset_path: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg
-          asset_name: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg
-          asset_content_type: application/octet-stream
+      # - name: Build FreeBSD package
+      #   if: matrix.build == 'freebsd'
+      #   uses: defGuard/fpm-action@main
+      #   with:
+      #     fpm_args:
+      #       "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/local/sbin/defguard-gateway
+      #       defguard-gateway.service.freebsd=/usr/local/etc/rc.d/defguard_gateway
+      #       example-config.toml=/etc/defguard/gateway.toml.sample
+      #       defguard-rc.conf=/etc/rc.conf.d/defguard_gateway"
+      #     fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type freebsd --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg --freebsd-osversion '*'"
 
-      - name: Build OPNsense package
-        if: matrix.build == 'freebsd'
-        uses: defGuard/fpm-action@main
-        with:
-          fpm_args:
-            "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/local/sbin/defguard-gateway
-            defguard-gateway.service.freebsd=/usr/local/etc/rc.d/defguard_gateway
-            example-config.toml=/etc/defguard/gateway.toml.sample
-            defguard-rc.conf=/etc/rc.conf.d/defguard_gateway
-            opnsense/src/etc/=/usr/local/etc/
-            opnsense/src/opnsense/=/usr/local/opnsense/"
-          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type freebsd --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg --freebsd-osversion '*'"
+      # - name: Upload FreeBSD
+      #   if: matrix.build == 'freebsd'
+      #   uses: actions/upload-release-asset@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     upload_url: ${{ needs.create-release.outputs.upload_url }}
+      #     asset_path: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg
+      #     asset_name: defguard-gateway_${{ env.VERSION }}_${{ matrix.target }}.pkg
+      #     asset_content_type: application/octet-stream
 
-      - name: Upload OPNsense package
-        if: matrix.build == 'freebsd'
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ needs.create-release.outputs.upload_url }}
-          asset_path: defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg
-          asset_name: defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg
-          asset_content_type: application/octet-stream
+      # - name: Build OPNsense package
+      #   if: matrix.build == 'freebsd'
+      #   uses: defGuard/fpm-action@main
+      #   with:
+      #     fpm_args:
+      #       "${{ matrix.asset_name }}-${{ github.ref_name }}=/usr/local/sbin/defguard-gateway
+      #       defguard-gateway.service.freebsd=/usr/local/etc/rc.d/defguard_gateway
+      #       example-config.toml=/etc/defguard/gateway.toml.sample
+      #       defguard-rc.conf=/etc/rc.conf.d/defguard_gateway
+      #       opnsense/src/etc/=/usr/local/etc/
+      #       opnsense/src/opnsense/=/usr/local/opnsense/"
+      #     fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type freebsd --version ${{ env.VERSION }} --package defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg --freebsd-osversion '*'"
+
+      # - name: Upload OPNsense package
+      #   if: matrix.build == 'freebsd'
+      #   uses: actions/upload-release-asset@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     upload_url: ${{ needs.create-release.outputs.upload_url }}
+      #     asset_path: defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg
+      #     asset_name: defguard-gateway_${{ env.VERSION }}_x86_64-unknown-opnsense.pkg
+      #     asset_content_type: application/octet-stream
 
 
   apt-sign:
